import { Word } from './types';

export const vocabulary: Word[] = [
  // Les 1
  { id: '1-1', lesson: 1, term: 'afdalen', definition: 'Naar beneden gaan, bijvoorbeeld een trap af of een grot in.' },
  { id: '1-2', lesson: 1, term: 'de begane grond', definition: 'De verdieping die gelijk is met de straat (benedenverdieping).' },
  { id: '1-3', lesson: 1, term: 'de container', definition: 'Een hele grote bak om spullen in te vervoeren of afval in te gooien.' },
  { id: '1-4', lesson: 1, term: 'de dassenburcht', definition: 'Het ondergrondse huis van een das, met gangen en kamers.' },
  { id: '1-5', lesson: 1, term: 'de delfstof', definition: 'Nuttige stoffen die we uit de grond halen, zoals goud, zout of steenkool.' },
  { id: '1-6', lesson: 1, term: 'delven', definition: 'Iets uit de grond graven of halen.' },
  { id: '1-7', lesson: 1, term: 'de doorsnede', definition: 'Hoe iets er van binnen uitziet als je het doormidden zou snijden.' },
  { id: '1-8', lesson: 1, term: 'het edelmetaal', definition: 'Kostbaar metaal dat veel waard is, zoals goud en zilver.' },
  { id: '1-9', lesson: 1, term: 'het gangenstelsel', definition: 'Een netwerk van tunnels die met elkaar verbonden zijn.' },
  { id: '1-10', lesson: 1, term: 'het grondwater', definition: 'Het water dat diep in de bodem (onder de grond) zit.' },
  { id: '1-11', lesson: 1, term: 'de kruipruimte', definition: 'Een hele lage ruimte onder de vloer van een huis waar je alleen kunt kruipen.' },
  { id: '1-12', lesson: 1, term: 'de mijn', definition: 'Gangen diep onder de grond waar mensen delfstoffen (zoals steenkool) uithalen.' },
  { id: '1-13', lesson: 1, term: 'de mijnwerker', definition: 'Iemand die als beroep diep onder de grond werkt in een mijn.' },
  { id: '1-14', lesson: 1, term: 'onderaards', definition: 'Alles wat zich onder de grond bevindt.' },
  { id: '1-15', lesson: 1, term: 'de ondergrondse', definition: 'Een ander woord voor de metro (trein onder de grond).' },
  { id: '1-16', lesson: 1, term: 'opgraven', definition: 'Iets wat in de grond zit naar boven halen door te graven.' },
  { id: '1-17', lesson: 1, term: 'de schacht', definition: 'Een gegraven gat recht naar beneden de grond in (bijvoorbeeld in een mijn).' },
  { id: '1-18', lesson: 1, term: 'het souterrain', definition: 'Een verdieping die half onder de grond ligt (kelderverdieping met ramen).' },
  { id: '1-19', lesson: 1, term: 'de steenkool', definition: 'Een zwarte stof uit de grond die we gebruiken om energie (vuur/warmte) te maken.' },
  { id: '1-20', lesson: 1, term: 'de vluchtroute', definition: 'De weg die je moet nemen om veilig buiten te komen als er gevaar is.' },

  // Les 5
  { id: '5-1', lesson: 5, term: 'het afvalwater', definition: 'Water dat we gebruikt hebben en vies is geworden (bijvoorbeeld uit de wc of douche).' },
  { id: '5-2', lesson: 5, term: 'de afvoer', definition: 'Het buisje waar het water door wegloopt uit de gootsteen.' },
  { id: '5-3', lesson: 5, term: 'de archeoloog', definition: 'Iemand die oude spullen uit de grond opgraaft om de geschiedenis te leren.' },
  { id: '5-4', lesson: 5, term: 'de beerput', definition: 'Een put waar vroeger de poep en plas in werd verzameld (toen er nog geen riool was).' },
  { id: '5-5', lesson: 5, term: 'de drek', definition: 'Vies, dik en modderig spul. Een ander woord voor viezigheid.' },
  { id: '5-6', lesson: 5, term: 'het fossiel', definition: 'Versteende resten van planten of dieren van heel lang geleden.' },
  { id: '5-7', lesson: 5, term: 'het gewelf', definition: 'Een gebogen plafond, vaak gemaakt van stenen in een boog.' },
  { id: '5-8', lesson: 5, term: 'grondig', definition: 'Heel precies en goed. Je slaat niets over.' },
  { id: '5-9', lesson: 5, term: 'het hemelwater', definition: 'Water dat uit de lucht valt, zoals regen, sneeuw of hagel.' },
  { id: '5-10', lesson: 5, term: 'lozen', definition: 'Vies water weg laten stromen in de rivier of het riool.' },
  { id: '5-11', lesson: 5, term: 'muf', definition: 'Een vieze geur, niet fris. Het ruikt naar een kamer waar nooit een raam open staat.' },
  { id: '5-12', lesson: 5, term: 'overlopen', definition: 'Als er te veel water in zit, stroomt het over de rand.' },
  { id: '5-13', lesson: 5, term: 'overtollig', definition: 'Meer dan nodig is. Wat je te veel hebt.' },
  { id: '5-14', lesson: 5, term: 'het riool', definition: 'Buizen onder de grond die al ons vieze water afvoeren.' },
  { id: '5-15', lesson: 5, term: 'de smurrie', definition: 'Een vies, plakkerig en nat mengsel.' },
  { id: '5-16', lesson: 5, term: 'het straatniveau', definition: 'De hoogte waarop de straat ligt.' },
  { id: '5-17', lesson: 5, term: 'verontreinigd', definition: 'Vervuild. Er zitten stoffen in die er niet horen (vies).' },
  { id: '5-18', lesson: 5, term: 'versteend', definition: 'Iets wat na heel lange tijd hard is geworden als steen.' },
  { id: '5-19', lesson: 5, term: 'het waterpeil', definition: 'De hoogte van het water (hoe hoog het water staat).' },
  { id: '5-20', lesson: 5, term: 'zuiveren', definition: 'Schoonmaken. Zorgen dat vieze stoffen uit het water gaan.' },
];